spring.datasource.url=jdbc:postgresql://dpg-db0s3dk9v7es73cpqq8g-a:5432/crud_db_ahlr?sslmode=require
spring.datasource.username=usuario_crud
spring.datasource.password=CB8KWvvgQBIW1a2JfVYxsx2r00uHtcm2

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect